export default [
  "Forge a suit of plate armor for a noble knight",
  "Transcribe ancient manuscripts from Latin to the common tongue",
  "Craft a potion to cure a village plagued by illness",
  "Design a crest and coat of arms for a noble house",
  "Write an epic poem recounting the heroic deeds of a legendary knight",
  "Scribe a map of uncharted lands for a brave explorer",
  "Create a tapestry depicting the history of a kingdom",
  "Build a trebuchet for the defense of a castle",
  "Compose a song to entertain the court during a royal banquet",
  "Carve intricate wooden figurines to adorn a king's throne room",
  "Brew a batch of mead fit for a royal celebration",
  "Illustrate a bestiary cataloging mythical creatures of the realm",
  "Craft enchanted jewelry imbued with protective spells",
  "Write a scroll detailing the laws and customs of a medieval town",
  "Design a medieval village layout optimizing defense and functionality",
  "Create illuminated manuscripts for a monastery's library",
  "Carve intricate designs into the hilt of a noble's sword",
  "Forge a mystical artifact to aid a questing adventurer",
  "Sculpt gargoyles to adorn the battlements of a cathedral",
  "Compose a hymn for a religious ceremony in the grand cathedral",
  "Illustrate a map of a kingdom's borders and territories",
  "Craft a crown for the coronation of a new monarch",
  "Paint a mural depicting the founding myth of a kingdom",
  "Design a medieval-style tapestry to hang in a lord's great hall",
  "Create a manuscript of herbal remedies for a village apothecary",
  "Carve intricate designs into the pews of a medieval church",
  "Write a ballad recounting the tragic love story of star-crossed lovers",
  "Craft chainmail armor for a band of mercenaries",
  "Scribe a treaty to bring peace between warring factions",
  "Design a medieval-style banner to rally troops on the battlefield",
];
